spring:
  application:
    name: Ani-Graph
  datasource:
    url: jdbc:mysql://192.168.1.111:3306/anigraph?serverTimezone=GMT%2b8
    username: root
    password: Thewind266
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 8000